import { GithubLoginButton } from "@/components/auth/github-login-button";
import { Button } from "@/components/ui/button";
import {
	ArrowRight,
	BookOpen,
	CheckCircle,
	Clock,
	Code,
	GitBranch,
	Shield,
	Sparkles,
	Star,
	Users,
	Zap,
} from "lucide-react";
import Link from "next/link";

export default function LandingPage() {
	return (
		<div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-800">
			{/* Navigation */}
			<nav className="border-b bg-white/80 backdrop-blur-sm dark:bg-slate-900/80">
				<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
					<div className="flex h-16 items-center justify-between">
						<div className="flex items-center space-x-2">
							<div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
								<BookOpen className="h-5 w-5 text-primary-foreground" />
							</div>
							<span className="font-bold text-xl">Clio</span>
						</div>
						<div className="flex items-center space-x-4">
							<GithubLoginButton />
						</div>
					</div>
				</div>
			</nav>

			{/* Hero Section */}
			<section className="relative overflow-hidden py-20 sm:py-32">
				<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
					<div className="text-center">
						<h1 className="font-bold text-4xl text-gray-900 tracking-tight sm:text-6xl dark:text-white">
							Generate Beautiful{" "}
							<span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
								READMEs
							</span>{" "}
							with AI
						</h1>
						<p className="mx-auto mt-6 max-w-2xl text-gray-600 text-lg leading-8 dark:text-gray-300">
							Transform your GitHub repositories with comprehensive,
							professional README files generated by AI. No more blank READMEs
							or hours of manual writing.
						</p>
						<div className="mt-10 flex items-center justify-center gap-x-6">
							<GithubLoginButton className="px-8 py-3 text-lg" />
							<Button variant="outline" size="lg" asChild>
								<Link href="#features">
									Learn More <ArrowRight className="ml-2 h-4 w-4" />
								</Link>
							</Button>
						</div>
					</div>
				</div>

				{/* Background decoration */}
				<div className="-z-10 absolute inset-0 overflow-hidden">
					<div className="-translate-x-1/2 absolute top-0 left-[max(50%,25rem)] h-[64rem] w-[128rem] stroke-gray-200 [mask-image:radial-gradient(64rem_64rem_at_top,white,transparent)] dark:stroke-gray-700">
						<svg className="absolute inset-0 h-full w-full" aria-hidden="true">
							<defs>
								<pattern
									id="hero-pattern"
									width="200"
									height="200"
									x="50%"
									y="-1"
									patternUnits="userSpaceOnUse"
								>
									<path d="M.5 200V.5H200" fill="none" />
								</pattern>
							</defs>
							<svg
								x="50%"
								y="-1"
								className="overflow-visible fill-gray-50 dark:fill-gray-800"
								aria-hidden="true"
							>
								<path
									d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 400h201v201h-201Z M200 400h201v201h-201Z"
									strokeWidth="0"
								/>
							</svg>
							<rect
								width="100%"
								height="100%"
								strokeWidth="0"
								fill="url(#hero-pattern)"
							/>
						</svg>
					</div>
				</div>
			</section>

			{/* Features Section */}
			<section id="features" className="py-20 sm:py-32">
				<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
					<div className="text-center">
						<h2 className="font-bold text-3xl text-gray-900 tracking-tight sm:text-4xl dark:text-white">
							Why Choose Clio?
						</h2>
						<p className="mt-4 text-gray-600 text-lg dark:text-gray-300">
							Powerful features that make README generation effortless
						</p>
					</div>

					<div className="mt-20 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
						<div className="relative rounded-2xl bg-white p-8 shadow-lg dark:bg-slate-800">
							<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100 dark:bg-blue-900">
								<Zap className="h-6 w-6 text-blue-600 dark:text-blue-400" />
							</div>
							<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
								Lightning Fast
							</h3>
							<p className="mt-4 text-gray-600 dark:text-gray-300">
								Generate comprehensive READMEs in seconds, not hours. Our AI
								analyzes your code and creates professional documentation
								instantly.
							</p>
						</div>

						<div className="relative rounded-2xl bg-white p-8 shadow-lg dark:bg-slate-800">
							<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-green-100 dark:bg-green-900">
								<GitBranch className="h-6 w-6 text-green-600 dark:text-green-400" />
							</div>
							<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
								GitHub Integration
							</h3>
							<p className="mt-4 text-gray-600 dark:text-gray-300">
								Seamlessly connect with your GitHub repositories. Works with
								public, private, and organization repositories.
							</p>
						</div>

						<div className="relative rounded-2xl bg-white p-8 shadow-lg dark:bg-slate-800">
							<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-purple-100 dark:bg-purple-900">
								<Sparkles className="h-6 w-6 text-purple-600 dark:text-purple-400" />
							</div>
							<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
								AI-Powered
							</h3>
							<p className="mt-4 text-gray-600 dark:text-gray-300">
								Advanced AI analyzes your codebase, dependencies, and structure
								to create contextually relevant documentation.
							</p>
						</div>

						<div className="relative rounded-2xl bg-white p-8 shadow-lg dark:bg-slate-800">
							<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-orange-100 dark:bg-orange-900">
								<Shield className="h-6 w-6 text-orange-600 dark:text-orange-400" />
							</div>
							<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
								Secure & Private
							</h3>
							<p className="mt-4 text-gray-600 dark:text-gray-300">
								Your code stays private. We use secure GitHub App integration
								and never store your source code.
							</p>
						</div>

						<div className="relative rounded-2xl bg-white p-8 shadow-lg dark:bg-slate-800">
							<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-red-100 dark:bg-red-900">
								<Clock className="h-6 w-6 text-red-600 dark:text-red-400" />
							</div>
							<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
								Asynchronous Processing
							</h3>
							<p className="mt-4 text-gray-600 dark:text-gray-300">
								Large repositories are processed in the background. Get notified
								when your README is ready.
							</p>
						</div>

						<div className="relative rounded-2xl bg-white p-8 shadow-lg dark:bg-slate-800">
							<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-indigo-100 dark:bg-indigo-900">
								<Code className="h-6 w-6 text-indigo-600 dark:text-indigo-400" />
							</div>
							<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
								Customizable
							</h3>
							<p className="mt-4 text-gray-600 dark:text-gray-300">
								Choose from multiple styles, add custom prompts, and customize
								the output to match your project's needs.
							</p>
						</div>
					</div>
				</div>
			</section>

			{/* How It Works Section */}
			<section className="bg-gray-50 py-20 sm:py-32 dark:bg-slate-900">
				<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
					<div className="text-center">
						<h2 className="font-bold text-3xl text-gray-900 tracking-tight sm:text-4xl dark:text-white">
							How It Works
						</h2>
						<p className="mt-4 text-gray-600 text-lg dark:text-gray-300">
							Get started in three simple steps
						</p>
					</div>

					<div className="mt-20">
						<div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
							<div className="text-center">
								<div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-primary-foreground">
									<span className="font-bold text-2xl">1</span>
								</div>
								<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
									Connect GitHub
								</h3>
								<p className="mt-4 text-gray-600 dark:text-gray-300">
									Sign in with GitHub and install our app to access your
									repositories securely.
								</p>
							</div>

							<div className="text-center">
								<div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-primary-foreground">
									<span className="font-bold text-2xl">2</span>
								</div>
								<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
									Select Repository
								</h3>
								<p className="mt-4 text-gray-600 dark:text-gray-300">
									Choose any repository from your GitHub account and customize
									generation options.
								</p>
							</div>

							<div className="text-center">
								<div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-primary text-primary-foreground">
									<span className="font-bold text-2xl">3</span>
								</div>
								<h3 className="mt-6 font-semibold text-gray-900 text-xl dark:text-white">
									Get Your README
								</h3>
								<p className="mt-4 text-gray-600 dark:text-gray-300">
									Download your professionally generated README or copy it
									directly to your repository.
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* Stats Section */}
			<section className="py-20 sm:py-32">
				<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
					<div className="grid grid-cols-1 gap-8 sm:grid-cols-3">
						<div className="text-center">
							<div className="font-bold text-4xl text-primary sm:text-5xl">
								1000+
							</div>
							<div className="mt-2 text-gray-600 text-lg dark:text-gray-300">
								Repositories Processed
							</div>
						</div>
						<div className="text-center">
							<div className="font-bold text-4xl text-primary sm:text-5xl">
								500+
							</div>
							<div className="mt-2 text-gray-600 text-lg dark:text-gray-300">
								Happy Developers
							</div>
						</div>
						<div className="text-center">
							<div className="font-bold text-4xl text-primary sm:text-5xl">
								99.9%
							</div>
							<div className="mt-2 text-gray-600 text-lg dark:text-gray-300">
								Uptime
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* CTA Section */}
			<section className="bg-primary py-20 sm:py-32">
				<div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
					<div className="text-center">
						<h2 className="font-bold text-3xl text-white tracking-tight sm:text-4xl">
							Ready to Transform Your Repositories?
						</h2>
						<p className="mt-4 text-lg text-primary-foreground/90">
							Join thousands of developers who have already improved their
							documentation with Clio.
						</p>
						<div className="mt-10">
							<GithubLoginButton className="bg-white px-8 py-3 text-lg text-primary hover:bg-gray-100" />
						</div>
					</div>
				</div>
			</section>

			{/* Footer */}
			<footer className="bg-gray-900 text-white">
				<div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
					<div className="grid grid-cols-1 gap-8 sm:grid-cols-3">
						<div>
							<div className="flex items-center space-x-2">
								<div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
									<BookOpen className="h-5 w-5 text-primary-foreground" />
								</div>
								<span className="font-bold text-xl">Clio</span>
							</div>
							<p className="mt-4 text-gray-400">
								The AI-powered README generator that transforms your GitHub
								repositories with professional documentation.
							</p>
						</div>
						<div>
							<h3 className="font-semibold text-lg">Product</h3>
							<ul className="mt-4 space-y-2 text-gray-400">
								<li>
									<Link href="#features" className="hover:text-white">
										Features
									</Link>
								</li>
								<li>
									<Link href="#pricing" className="hover:text-white">
										Pricing
									</Link>
								</li>
								<li>
									<Link href="#docs" className="hover:text-white">
										Documentation
									</Link>
								</li>
							</ul>
						</div>
						<div>
							<h3 className="font-semibold text-lg">Support</h3>
							<ul className="mt-4 space-y-2 text-gray-400">
								<li>
									<Link href="#help" className="hover:text-white">
										Help Center
									</Link>
								</li>
								<li>
									<Link href="#contact" className="hover:text-white">
										Contact
									</Link>
								</li>
								<li>
									<Link href="#privacy" className="hover:text-white">
										Privacy Policy
									</Link>
								</li>
							</ul>
						</div>
					</div>
					<div className="mt-8 border-gray-800 border-t pt-8 text-center text-gray-400">
						<p>&copy; 2024 Clio. All rights reserved.</p>
					</div>
				</div>
			</footer>
		</div>
	);
}
